name: 'NPM install cache'
author: 'c-hive'
description: '1-liner npm install cache for GitHub Actions'
icon: 'box'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
